org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.248
neo_version_range=[21.1,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

alexsmobs_version=1.22.9
citadel_version=1.21.1-2.7.1

mod_id=alexsmobsinteraction
mod_name=Alex's Mobs Interaction
mod_license=MIT
mod_version=6.0
mod_group_id=com.crimsoncrips
mod_authors=The Crimson,Reimainder,Drullkus
mod_description=An addon that adds tons of new features specifically for the mod Alex's Mobs
