
modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''
[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId="minecraft"
mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
[[dependencies."${mod_id}"]]
modId="alexsmobs"
mandatory=true
versionRange="[1.22.9,)"
ordering="BEFORE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="curiouslanterns"
mandatory=false
versionRange="[1.20.1-1.3.3,)"
ordering="BEFORE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="soul_fire_d"
mandatory=false
versionRange="[4.0.6,)"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="biomesoplenty"
mandatory=false
versionRange="[19.0.0.91,)"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="curios"
mandatory=false
versionRange="[5.11.0+1.20.1,)"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId = "alexscaves"
mandatory = false
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange = "[2.0.2,)"
ordering = "NONE"
side = "BOTH"
