package com.crimsoncrips.alexsmobsinteraction.config;

import static com.mojang.text2speech.Narrator.LOGGER;

public class AMInteractionConfig {
    public static boolean MANTIS_SPEED_ENABLED = true;
    public static boolean BRUSHED_ENABLED = true;
    public static boolean anacondacanibalize = true;
    public static boolean EAGLE_CANNIBALIZE_ENABLED = true;
    public static boolean BANANA_SHEAR_ENABLED = true;
    public static boolean BLOODED_ENABLED = true;
    public static boolean CAIMAN_AGGRO_ENABLED = true;
    public static boolean CAPUCHIN_HUNT_ENABLED = true;
    public static boolean CATFISH_CANNIBALIZE_ENABLED = true;
    public static boolean STUPID_CATFISH_EAT_ENABLED = false;
    public static boolean LIGHT_FEAR_ENABLED = true;
    public static boolean CRIMSON_NON_STRADDLER_ENABLED = true;
    public static boolean CROW_CANNIBALIZE_ENABLED = true;
    public static boolean ELEPHANT_TERRITORIAL_ENABLED = true;
    public static boolean RANGED_AGGRO_ENABLED = true;
    public static boolean EMU_SCUFFLE_ENABLED = true;
    public static boolean FARSEER_ALTERING_ENABLED = true;
    public static boolean FARSEER_HUMANLIKE_ATTACK_ENABLED = true;
    public static boolean TUSKLIN_FLEE_ENABLED = true;
    public static boolean FLUTTER_WITHERED_ENABLED = true;
    public static boolean FLY_FEAR_ENABLED = true;
    public static boolean CANDLE_REPEL_ENABLED = true;
    public static boolean SQUID_CANNIBALIZE_ENABLED = true;
    public static boolean GRIZZLY_FRIENDLY_ENABLED = true;
    public static boolean GUSTER_WEIGHT_ENABLED = true;
    public static boolean HAMMERHEAD_MANTIS_EAT_ENABLED = true;
    public static boolean POLINATE_DAY_ENABLED = true;
    public static boolean LOBSTER_NIGHT_ENABLED = true;
    public static boolean MANTIS_AGGRO_ENABLED = true;
    public static boolean MANTIS_CANNIBALIZE_ENABLED = true;
    public static boolean MURMUR_REGROW_ENABLED = true;
    public static boolean DROPLESS_PREDATOR_ENABLED = true;
    public static boolean PREY_FEAR_ENABLED = true;
    public static boolean RACOON_HUNT_ENABLED = true;
    public static boolean RATTLESNAKE_CANNIBALIZE_ENABLED = true;
    public static boolean ROADRUNNER_DAY_ENABLED = true;
    public static boolean MIGHT_UPGRADE_ENABLED = true;
    public static boolean SEAGULL_BUFFED_ENABLED = true;
    public static boolean SEAGULL_WEAKEN_ENABLED = true;
    public static boolean SKITTISH_ROACHES_ENABLED = true;
    public static boolean SNAPPING_ALERT_ENABLED = true;
    public static boolean SNAPPING_DORMANT_ENABLED = true;
    public static boolean SPIDER_EAT_ENABLED = true;
    public static boolean STRADDLER_VENGEANCE_ENABLED = true;
    public static boolean STRADPOLE_BOB_UP_ENABLED = true;
    public static boolean SUGAR_RUSH_ENABLED = true;
    public static boolean TERRAPIN_STOMP_ENABLED = true;
    public static boolean MOSCO_CANNIBALISM_ENABLED = true;
    public static int STRADDLER_SHOTS_AMOUNT = 8;
    public static boolean WARPED_FRIENDLY_ENABLED = true;
    public static boolean CAVESPIDER_EAT_ENABLED = true;
    public static boolean EMU_EGG_ATTACK_ENABLED = true;

    public static boolean SERPENT_FEAR_ENABLED = true;
    public static boolean MUDSKIPPER_HUNT_ENABLED = true;
    public static boolean CAIMAN_EGG_ATTACK_ENABLED = true;
    public static boolean HUMMING_FOLLOW_ENABLED = true;

    public static boolean FLY_PESTER_ENABLED = true;
    public static boolean SOMBRERO_PROTECTION_ENABLED = true;
    public static boolean INFECT_WEAK_ENABLED = true;
    public static boolean INFECT_IMMUNITY_ENABLED = true;
    public static boolean FLUTTER_SHEAR_ENABLED = true;
    public static boolean GELADA_HUNT_ENABLED = true;
    public static boolean ORCA_HUNT_ENABLED = true;
    public static boolean CRIMSON_TRANSFORM_ENABLED = true;
    public static boolean FROG_TRANSFORM_ENABLED = true;
    public static boolean SNAPPING_MOSS_ENABLED = true;
    public static boolean SKELEWAG_CIRCLE_ENABLED = true;
    public static boolean CHARGE_STUN_ENABLED = true;
    public static boolean TUSKLIN_TRUST_ENABLED = true;
    public static boolean FLY_CONVERT_ENABLED = true;
    public static boolean BLOOD_PROTECTION_ENABLED = true;
    public static boolean SNOW_LUCK_ENABLED = true;
    public static boolean VULTURE_STEAL_ENABLED = true;
    public static boolean SKREECHER_WARD_ENABLED = true;
    public static boolean POCKET_SAND_AMMOLESS_ENABLED = true;
    public static boolean OBSIDIAN_EXTRACT_ENABLED = true;
    public static boolean TUSKLIN_TRAMPLE_ENABLED = true;
    public static boolean REMOVE_TUSKLIN_EQUIPMENT_ENABLED = true;
    public static boolean GUSTER_PROJECTILE_PROT_ENABLED = true;
    public static boolean ELEPHANT_TRAMPLE_ENABLED = true;
    public static boolean VOIDWORM_STUN_ENABLED = true;
    public static boolean GOOFY_STRADDLER_SHOTGUN_ENABLED = true;
    public static boolean FREDDYABLE_ENABLED = true;

    public static boolean STRADPOLE_FLAME_ENABLED = true;
    public static boolean GOOFY_MODE_ENABLED = true;
    public static boolean GOOFY_BANANA_SLIP_ENABLED = true;
    public static boolean COSMAW_WEAKENED_ENABLED = true;
    public static boolean GOOFY_MURMUR_DECAPITATED_ENABLED = true;
    public static boolean GOOFY_CRIMSON_MULTIPLY_ENABLED = true;
    public static boolean RAINFROG_SPAWNAGE_ENABLED = true;
    public static boolean TIGER_STEALTH_ENABLED = true;
    public static boolean SUNBIRD_UPGRADE_ENABLED = true;
    public static boolean LEOPARD_DESIRES_ENABLED = true;
    public static boolean GOOFY_CAPUCHIN_BOMB_ENABLED = true;
    public static boolean DIMENSIONAL_LODESTONE_ENABLED = true;
    public static boolean ROLLING_THUNDER_ENABLED = true;


    public static void bake() {
        try {
            MANTIS_SPEED_ENABLED = AMIConfigHolder.INTERACT.MANTIS_SPEED_ENABLED.get();
            BRUSHED_ENABLED = AMIConfigHolder.INTERACT.BRUSHED_ENABLED.get();
            ROLLING_THUNDER_ENABLED = AMIConfigHolder.INTERACT.ROLLING_THUNDER_ENABLED.get();
            DIMENSIONAL_LODESTONE_ENABLED = AMIConfigHolder.INTERACT.DIMENSIONAL_LODESTONE_ENABLED.get();
            GOOFY_CAPUCHIN_BOMB_ENABLED = AMIConfigHolder.INTERACT.GOOFY_CAPUCHIN_BOMB_ENABLED.get();
            LEOPARD_DESIRES_ENABLED = AMIConfigHolder.INTERACT.LEOPARD_DESIRES_ENABLED.get();
            SUNBIRD_UPGRADE_ENABLED = AMIConfigHolder.INTERACT.SUNBIRD_UPGRADE_ENABLED.get();
            TIGER_STEALTH_ENABLED = AMIConfigHolder.INTERACT.TIGER_STEALTH_ENABLED.get();
            RAINFROG_SPAWNAGE_ENABLED = AMIConfigHolder.INTERACT.RAINFROG_SPAWNAGE_ENABLED.get();
            GOOFY_CRIMSON_MULTIPLY_ENABLED = AMIConfigHolder.INTERACT.GOOFY_CRIMSON_MULTIPLY_ENABLED.get();
            GOOFY_MURMUR_DECAPITATED_ENABLED = AMIConfigHolder.INTERACT.GOOFY_MURMUR_DECAPITATED_ENABLED.get();
            COSMAW_WEAKENED_ENABLED = AMIConfigHolder.INTERACT.COSMAW_WEAKENED_ENABLED.get();
            GOOFY_BANANA_SLIP_ENABLED = AMIConfigHolder.INTERACT.GOOFY_BANANA_SLIP_ENABLED.get();
            GOOFY_MODE_ENABLED = AMIConfigHolder.INTERACT.GOOFY_MODE_ENABLED.get();
            STRADPOLE_FLAME_ENABLED = AMIConfigHolder.INTERACT.STRADPOLE_FLAME_ENABLED.get();
            FREDDYABLE_ENABLED = AMIConfigHolder.INTERACT.FREDDYABLE_ENABLED.get();
            GOOFY_STRADDLER_SHOTGUN_ENABLED = AMIConfigHolder.INTERACT.GOOFY_STRADDLER_SHOTGUN_ENABLED.get();
            VOIDWORM_STUN_ENABLED = AMIConfigHolder.INTERACT.VOIDWORM_STUN_ENABLED.get();
            ELEPHANT_TRAMPLE_ENABLED = AMIConfigHolder.INTERACT.ELEPHANT_TRAMPLE_ENABLED.get();
            GUSTER_PROJECTILE_PROT_ENABLED = AMIConfigHolder.INTERACT.GUSTER_PROJECTILE_PROT_ENABLED.get();
            REMOVE_TUSKLIN_EQUIPMENT_ENABLED = AMIConfigHolder.INTERACT.REMOVE_TUSKLIN_EQUIPMENT_ENABLED.get();
            TUSKLIN_TRAMPLE_ENABLED = AMIConfigHolder.INTERACT.TUSKLIN_TRAMPLE_ENABLED.get();
            OBSIDIAN_EXTRACT_ENABLED = AMIConfigHolder.INTERACT.OBSIDIAN_EXTRACT_ENABLED.get();
            POCKET_SAND_AMMOLESS_ENABLED = AMIConfigHolder.INTERACT.POCKET_SAND_AMMOLESS_ENABLED.get();
            SKREECHER_WARD_ENABLED = AMIConfigHolder.INTERACT.SKREECHER_WARD_ENABLED.get();
            VULTURE_STEAL_ENABLED = AMIConfigHolder.INTERACT.VULTURE_STEAL_ENABLED.get();
            SNOW_LUCK_ENABLED = AMIConfigHolder.INTERACT.SNOW_LUCK_ENABLED.get();
            BLOOD_PROTECTION_ENABLED = AMIConfigHolder.INTERACT.BLOOD_PROTECTION_ENABLED.get();
            FLY_CONVERT_ENABLED = AMIConfigHolder.INTERACT.FLY_CONVERT_ENABLED.get();
            TUSKLIN_TRUST_ENABLED = AMIConfigHolder.INTERACT.TUSKLIN_TRUST_ENABLED.get();
            CHARGE_STUN_ENABLED = AMIConfigHolder.INTERACT.CHARGE_STUN_ENABLED.get();
            SKELEWAG_CIRCLE_ENABLED = AMIConfigHolder.INTERACT.SKELEWAG_CIRCLE_ENABLED.get();
            SNAPPING_MOSS_ENABLED = AMIConfigHolder.INTERACT.SNAPPING_MOSS_ENABLED.get();
            FROG_TRANSFORM_ENABLED = AMIConfigHolder.INTERACT.FROG_TRANSFORM_ENABLED.get();
            CRIMSON_TRANSFORM_ENABLED = AMIConfigHolder.INTERACT.CRIMSON_TRANSFORM_ENABLED.get();
            ORCA_HUNT_ENABLED = AMIConfigHolder.INTERACT.ORCA_HUNT_ENABLED.get();
            FLY_PESTER_ENABLED = AMIConfigHolder.INTERACT.FLY_PESTER_ENABLED.get();
            GELADA_HUNT_ENABLED = AMIConfigHolder.INTERACT.GELADA_HUNT_ENABLED.get();
            SOMBRERO_PROTECTION_ENABLED = AMIConfigHolder.INTERACT.SOMBRERO_PROTECTION_ENABLED.get();
            INFECT_WEAK_ENABLED = AMIConfigHolder.INTERACT.INFECT_WEAK_ENABLED.get();
            INFECT_IMMUNITY_ENABLED = AMIConfigHolder.INTERACT.INFECT_IMMUNITY_ENABLED.get();
            FLUTTER_SHEAR_ENABLED = AMIConfigHolder.INTERACT.FLUTTER_SHEAR_ENABLED.get();
            anacondacanibalize = AMIConfigHolder.INTERACT.ANACONDA_CANNIBALIZE_ENABLED.get();
            EAGLE_CANNIBALIZE_ENABLED = AMIConfigHolder.INTERACT.EAGLE_CANNIBALIZE_ENABLED.get();
            BANANA_SHEAR_ENABLED = AMIConfigHolder.INTERACT.BANANA_SHEAR_ENABLED.get();
            BLOODED_ENABLED = AMIConfigHolder.INTERACT.BLOODED_ENABLED.get();
            CAIMAN_AGGRO_ENABLED = AMIConfigHolder.INTERACT.CAIMAN_AGGRO_ENABLED.get();
            CAPUCHIN_HUNT_ENABLED = AMIConfigHolder.INTERACT.CAPUCHIN_HUNT_ENABLED.get();
            CATFISH_CANNIBALIZE_ENABLED = AMIConfigHolder.INTERACT.CATFISH_CANNIBALIZE_ENABLED.get();
            STUPID_CATFISH_EAT_ENABLED = AMIConfigHolder.INTERACT.STUPID_CATFISH_EAT_ENABLED.get();
            LIGHT_FEAR_ENABLED = AMIConfigHolder.INTERACT.LIGHT_FEAR_ENABLED.get();
            CRIMSON_NON_STRADDLER_ENABLED = AMIConfigHolder.INTERACT.CRIMSON_NON_STRADDLER_ENABLED.get();
            CROW_CANNIBALIZE_ENABLED = AMIConfigHolder.INTERACT.CROW_CANNIBALIZE_ENABLED.get();
            ELEPHANT_TERRITORIAL_ENABLED = AMIConfigHolder.INTERACT.ELEPHANT_TERRITORIAL_ENABLED.get();
            RANGED_AGGRO_ENABLED = AMIConfigHolder.INTERACT.RANGED_AGGRO_ENABLED.get();
            EMU_SCUFFLE_ENABLED = AMIConfigHolder.INTERACT.EMU_SCUFFLE_ENABLED.get();
            FARSEER_ALTERING_ENABLED = AMIConfigHolder.INTERACT.FARSEER_ALTERING_ENABLED.get();
            FARSEER_HUMANLIKE_ATTACK_ENABLED = AMIConfigHolder.INTERACT.FARSEER_HUMANLIKE_ATTACK_ENABLED.get();
            TUSKLIN_FLEE_ENABLED = AMIConfigHolder.INTERACT.TUSKLIN_FLEE_ENABLED.get();
            FLUTTER_WITHERED_ENABLED = AMIConfigHolder.INTERACT.FLUTTER_WITHERED_ENABLED.get();
            FLY_FEAR_ENABLED = AMIConfigHolder.INTERACT.FLY_FEAR_ENABLED.get();
            CANDLE_REPEL_ENABLED = AMIConfigHolder.INTERACT.CANDLE_REPEL_ENABLED.get();
            SQUID_CANNIBALIZE_ENABLED = AMIConfigHolder.INTERACT.SQUID_CANNIBALIZE_ENABLED.get();
            GRIZZLY_FRIENDLY_ENABLED = AMIConfigHolder.INTERACT.GRIZZLY_FRIENDLY_ENABLED.get();
            GUSTER_WEIGHT_ENABLED = AMIConfigHolder.INTERACT.GUSTER_WEIGHT_ENABLED.get();
            HAMMERHEAD_MANTIS_EAT_ENABLED = AMIConfigHolder.INTERACT.HAMMERHEAD_MANTIS_EAT_ENABLED.get();
            POLINATE_DAY_ENABLED = AMIConfigHolder.INTERACT.POLINATE_DAY_ENABLED.get();
            LOBSTER_NIGHT_ENABLED = AMIConfigHolder.INTERACT.LOBSTER_NIGHT_ENABLED.get();
            MANTIS_AGGRO_ENABLED = AMIConfigHolder.INTERACT.MANTIS_AGGRO_ENABLED.get();
            MANTIS_CANNIBALIZE_ENABLED = AMIConfigHolder.INTERACT.MANTIS_CANNIBALIZE_ENABLED.get();
            MURMUR_REGROW_ENABLED = AMIConfigHolder.INTERACT.MURMUR_REGROW_ENABLED.get();
            DROPLESS_PREDATOR_ENABLED = AMIConfigHolder.INTERACT.DROPLESS_PREDATOR_ENABLED.get();
            PREY_FEAR_ENABLED = AMIConfigHolder.INTERACT.PREY_FEAR_ENABLED.get();
            RACOON_HUNT_ENABLED = AMIConfigHolder.INTERACT.RACOON_HUNT_ENABLED.get();
            RATTLESNAKE_CANNIBALIZE_ENABLED = AMIConfigHolder.INTERACT.RATTLESNAKE_CANNIBALIZE_ENABLED.get();
            ROADRUNNER_DAY_ENABLED = AMIConfigHolder.INTERACT.ROADRUNNER_DAY_ENABLED.get();
            MIGHT_UPGRADE_ENABLED = AMIConfigHolder.INTERACT.MIGHT_UPGRADE_ENABLED.get();
            SEAGULL_BUFFED_ENABLED = AMIConfigHolder.INTERACT.SEAGULL_BUFFED_ENABLED.get();
            SEAGULL_WEAKEN_ENABLED = AMIConfigHolder.INTERACT.SEAGULL_WEAKEN_ENABLED.get();
            SKITTISH_ROACHES_ENABLED = AMIConfigHolder.INTERACT.SKITTISH_ROACHES_ENABLED.get();
            SNAPPING_ALERT_ENABLED = AMIConfigHolder.INTERACT.SNAPPING_ALERT_ENABLED.get();
            SNAPPING_DORMANT_ENABLED = AMIConfigHolder.INTERACT.SNAPPING_DORMANT_ENABLED.get();
            SPIDER_EAT_ENABLED = AMIConfigHolder.INTERACT.SPIDER_EAT_ENABLED.get();
            STRADDLER_SHOTS_AMOUNT = AMIConfigHolder.INTERACT.STRADDLER_SHOTS_AMOUNT.get();
            STRADDLER_VENGEANCE_ENABLED = AMIConfigHolder.INTERACT.STRADDLER_VENGEANCE_ENABLED.get();
            STRADPOLE_BOB_UP_ENABLED = AMIConfigHolder.INTERACT.STRADPOLE_BOB_UP_ENABLED.get();
            SUGAR_RUSH_ENABLED = AMIConfigHolder.INTERACT.SUGAR_RUSH_ENABLED.get();
            TERRAPIN_STOMP_ENABLED = AMIConfigHolder.INTERACT.TERRAPIN_STOMP_ENABLED.get();
            MOSCO_CANNIBALISM_ENABLED = AMIConfigHolder.INTERACT.MOSCO_CANNIBALISM_ENABLED.get();
            WARPED_FRIENDLY_ENABLED = AMIConfigHolder.INTERACT.WARPED_FRIENDLY_ENABLED.get();
            CAVESPIDER_EAT_ENABLED = AMIConfigHolder.INTERACT.CAVESPIDER_EAT_ENABLED.get();
            EMU_EGG_ATTACK_ENABLED = AMIConfigHolder.INTERACT.EMU_EGG_ATTACK_ENABLED.get();
            CAIMAN_EGG_ATTACK_ENABLED = AMIConfigHolder.INTERACT.CAIMAN_EGG_ATTACK_ENABLED.get();
            MUDSKIPPER_HUNT_ENABLED = AMIConfigHolder.INTERACT.MUDSKIPPER_HUNT_ENABLED.get();
            HUMMING_FOLLOW_ENABLED = AMIConfigHolder.INTERACT.HUMMING_FOLLOW_ENABLED.get();




        } catch (Exception e) {
            LOGGER.warn("An exception was caused trying to load the config for Alex's Interaction.");
            e.printStackTrace();
        }
    }

}
