package com.crimsoncrips.alexsmobsinteraction.config;

import static com.mojang.text2speech.Narrator.LOGGER;

public class AMInteractionConfig {
    public static boolean anacondacanibalize = true;
    public static boolean baldeaglecannibalize = true;
    public static boolean bananaslugsheared = true;
    public static boolean bloodedmosquitoes = true;
    public static boolean bluejayhunt = true;
    public static boolean caimanaggresive = true;
    public static boolean capuchinhunt = true;
    public static boolean catfishcannibalize = true;
    public static boolean catfisheatstupid = false;
    public static boolean centipedelightfear = true;
    public static boolean crimsonnostraddler = true;
    public static boolean crowcannibalize = true;
    public static boolean elephantattack = true;
    public static boolean emurangedattack = true;
    public static boolean emuscuffle = true;
    public static boolean farseeralter = true;
    public static boolean farseerhumanlikeattack = true;
    public static boolean fleewarped = true;
    public static boolean flutterwither = true;
    public static boolean flyfearall = true;
    public static boolean flyfearcandles = true;
    public static boolean frogeatflies = true;
    public static boolean giantsquidcannibalize = true;
    public static boolean grizzlyattackfriendly = true;
    public static boolean gusterweighed = true;
    public static boolean hammerheadhuntmantisshrimp = true;
    public static boolean hummingbirdpolinate = true;
    public static boolean lobsternight = true;
    public static boolean mantisaggresive = true;
    public static boolean mantiscannibalize = true;
    public static boolean murmurbodykill = true;
    public static boolean nodropsforpredators = true;
    public static boolean preyfear = true;
    public static boolean raccoonhunt = true;
    public static boolean rattlesnakecannibalize = true;
    public static boolean roadrunnerday = true;
    public static boolean mightupgrade = true;
    public static boolean seagullbuff = true;
    public static boolean seagullnotsnatch = true;
    public static boolean skittishcockroaches = true;
    public static boolean snappingturtlealert = true;
    public static boolean snappingturtledormant = true;
    public static boolean spidereats = true;
    public static boolean stradllervengeance = true;
    public static boolean stradpolebobup = true;
    public static boolean sugarrush = true;
    public static boolean terrapinstomp = true;
    public static boolean tigerhuntnight = true;
    public static boolean warpedcannibalism = true;
    public static boolean weakened = true;
    public static int straddlershots = 8;
    public static boolean warpedtarantula = true;
    public static boolean cavespidereats = true;
    public static boolean emueggattack = true;

    public static boolean boneserpentfear = true;
    public static boolean mudskipperhunt = true;
    public static boolean caimaneggattack = true;
    public static boolean hummingfollowflutter = true;

    public static boolean flypester = true;
    public static boolean seagullsombrero = true;
    public static boolean enderiophageplayer = true;
    public static boolean enderioimmunity = true;
    public static boolean fluttersheared = true;
    public static boolean geladahunt = true;
    public static boolean orcahunt = true;
    public static boolean crimsontransform = true;
    public static boolean enderioadaption = true;
    public static boolean frogtransform = true;
    public static boolean snappingturtlemossincrease = true;
    public static boolean skelewagcircle = true;
    public static boolean stunnablecharge = true;
    public static boolean tusklinfulltrust = true;
    public static boolean flyconvert = true;
    public static boolean crimsonbloodprot = true;
    public static boolean snowluck = true;
    public static boolean soulbuff = true;
    public static boolean skreecherward = true;
    public static boolean sandnoammo = true;
    public static boolean lavaithanobsidianremove = true;
    public static boolean tusklintrample = true;
    public static boolean tusklinremoveequipment = true;
    public static boolean gusterprojectileprot = true;
    public static boolean elephanttrample = true;
    public static boolean voidwormstun = true;
    public static boolean straddlerexplosivespread = true;
    public static boolean grizzlyfreddy = true;

    public static boolean stradpoleflame = true;
    public static boolean goofymode = true;
    public static boolean bananaslip = true;
    public static boolean cosmawweakness = true;
    public static boolean murmurdecapitate = true;
    public static boolean crimsonmultiply = true;
    public static boolean rainfrogspawnage = true;
    public static boolean tigersstealth = true;
    public static boolean sunbirdupgrade = true;
    public static boolean leoparddesires = true;
    public static boolean capuchinbomb = true;
    public static boolean dimensionallodestone = true;
    public static boolean rollingthunder = true;


    public static void bake() {
        try {
            rollingthunder = AMIConfigHolder.INTERACT.rollingthunder.get();
            dimensionallodestone = AMIConfigHolder.INTERACT.dimensionallodestone.get();
            capuchinbomb = AMIConfigHolder.INTERACT.capuchinbomb.get();
            leoparddesires = AMIConfigHolder.INTERACT.leoparddesires.get();
            sunbirdupgrade = AMIConfigHolder.INTERACT.sunbirdupgrade.get();
            tigersstealth = AMIConfigHolder.INTERACT.tigersstealth.get();
            rainfrogspawnage = AMIConfigHolder.INTERACT.rainfrogspawnage.get();
            crimsonmultiply = AMIConfigHolder.INTERACT.crimsonmultiply.get();
            murmurdecapitate = AMIConfigHolder.INTERACT.murmurdecapitate.get();
            cosmawweakness = AMIConfigHolder.INTERACT.cosmawweakness.get();
            bananaslip = AMIConfigHolder.INTERACT.bananaslip.get();
            goofymode = AMIConfigHolder.INTERACT.goofymode.get();
            stradpoleflame = AMIConfigHolder.INTERACT.stradpoleflame.get();
            grizzlyfreddy = AMIConfigHolder.INTERACT.grizzlyfreddy.get();
            straddlerexplosivespread = AMIConfigHolder.INTERACT.straddlerexplosivespread.get();
            voidwormstun = AMIConfigHolder.INTERACT.voidwormstun.get();
            elephanttrample = AMIConfigHolder.INTERACT.elephanttrample.get();
            gusterprojectileprot = AMIConfigHolder.INTERACT.gusterprojectileprot.get();
            tusklinremoveequipment = AMIConfigHolder.INTERACT.tusklinremoveequipment.get();
            tusklintrample = AMIConfigHolder.INTERACT.tusklintrample.get();
            lavaithanobsidianremove = AMIConfigHolder.INTERACT.lavaithanobsidianremove.get();
            sandnoammo = AMIConfigHolder.INTERACT.sandnoammo.get();
            skreecherward = AMIConfigHolder.INTERACT.skreecherward.get();
            soulbuff = AMIConfigHolder.INTERACT.soulbuff.get();
            snowluck = AMIConfigHolder.INTERACT.snowluck.get();
            crimsonbloodprot = AMIConfigHolder.INTERACT.crimsonbloodprot.get();
            flyconvert = AMIConfigHolder.INTERACT.flyconvert.get();
            tusklinfulltrust = AMIConfigHolder.INTERACT.tusklinfulltrust.get();
            stunnablecharge = AMIConfigHolder.INTERACT.stunnablecharge.get();
            skelewagcircle = AMIConfigHolder.INTERACT.skelewagcircle.get();
            snappingturtlemossincrease = AMIConfigHolder.INTERACT.snappingturtlemossincrease.get();
            frogtransform = AMIConfigHolder.INTERACT.frogtransform.get();
            enderioadaption = AMIConfigHolder.INTERACT.enderioadaption.get();
            crimsontransform = AMIConfigHolder.INTERACT.crimsontransform.get();
            orcahunt = AMIConfigHolder.INTERACT.orcahunt.get();
            flypester = AMIConfigHolder.INTERACT.flypester.get();
            geladahunt = AMIConfigHolder.INTERACT.geladahunt.get();
            seagullsombrero = AMIConfigHolder.INTERACT.seagullsombrero.get();
            enderiophageplayer = AMIConfigHolder.INTERACT.enderiophageplayer.get();
            enderioimmunity = AMIConfigHolder.INTERACT.enderioimmunity.get();
            fluttersheared = AMIConfigHolder.INTERACT.fluttersheared.get();
            anacondacanibalize = AMIConfigHolder.INTERACT.anacondacannibalize.get();
            baldeaglecannibalize = AMIConfigHolder.INTERACT.baldeaglecannibalize.get();
            bananaslugsheared = AMIConfigHolder.INTERACT.bananaslugsheared.get();
            bloodedmosquitoes = AMIConfigHolder.INTERACT.bloodedmosquitoes.get();
            bluejayhunt = AMIConfigHolder.INTERACT.bluejayhunt.get();
            caimanaggresive = AMIConfigHolder.INTERACT.caimanaggresive.get();
            capuchinhunt = AMIConfigHolder.INTERACT.capuchinhunt.get();
            catfishcannibalize = AMIConfigHolder.INTERACT.catfishcannibalize.get();
            catfisheatstupid = AMIConfigHolder.INTERACT.catfisheatstupid.get();
            centipedelightfear = AMIConfigHolder.INTERACT.centipedelightfear.get();
            crimsonnostraddler = AMIConfigHolder.INTERACT.crimsonnostraddler.get();
            crowcannibalize = AMIConfigHolder.INTERACT.crowcannibalize.get();
            elephantattack = AMIConfigHolder.INTERACT.elephantattack.get();
            elephantattack = AMIConfigHolder.INTERACT.emurangedattack.get();
            emuscuffle = AMIConfigHolder.INTERACT.emuscuffle.get();
            farseeralter = AMIConfigHolder.INTERACT.farseeralter.get();
            farseerhumanlikeattack = AMIConfigHolder.INTERACT.farseerhumanlikeattack.get();
            fleewarped = AMIConfigHolder.INTERACT.fleewarped.get();
            flutterwither = AMIConfigHolder.INTERACT.flutterwither.get();
            flyfearall = AMIConfigHolder.INTERACT.flyfearall.get();
            flyfearcandles = AMIConfigHolder.INTERACT.flyfearcandles.get();
            frogeatflies = AMIConfigHolder.INTERACT.frogeatflies.get();
            giantsquidcannibalize = AMIConfigHolder.INTERACT.giantsquidcannibalize.get();
            grizzlyattackfriendly = AMIConfigHolder.INTERACT.grizzlyattackfriendly.get();
            gusterweighed = AMIConfigHolder.INTERACT.gusterweighed.get();
            hammerheadhuntmantisshrimp = AMIConfigHolder.INTERACT.hammerheadhuntmantisshrimp.get();
            hummingbirdpolinate = AMIConfigHolder.INTERACT.hummingbirdpolinate.get();
            lobsternight = AMIConfigHolder.INTERACT.lobsternight.get();
            mantisaggresive = AMIConfigHolder.INTERACT.mantisaggresive.get();
            mantiscannibalize = AMIConfigHolder.INTERACT.mantiscannibalize.get();
            murmurbodykill = AMIConfigHolder.INTERACT.murmurbodykill.get();
            nodropsforpredators = AMIConfigHolder.INTERACT.nodropsforpredators.get();
            preyfear = AMIConfigHolder.INTERACT.preyfear.get();
            raccoonhunt = AMIConfigHolder.INTERACT.raccoonhunt.get();
            rattlesnakecannibalize = AMIConfigHolder.INTERACT.rattlesnakecannibalize.get();
            roadrunnerday = AMIConfigHolder.INTERACT.roadrunnerday.get();
            mightupgrade = AMIConfigHolder.INTERACT.mightupgrade.get();
            seagullbuff = AMIConfigHolder.INTERACT.seagullbuff.get();
            seagullnotsnatch = AMIConfigHolder.INTERACT.seagullnotsnatch.get();
            skittishcockroaches = AMIConfigHolder.INTERACT.skittishcockroaches.get();
            snappingturtlealert = AMIConfigHolder.INTERACT.snappingturtlealert.get();
            snappingturtledormant = AMIConfigHolder.INTERACT.snappingturtledormant.get();
            spidereats = AMIConfigHolder.INTERACT.spidereats.get();
            straddlershots = AMIConfigHolder.INTERACT.straddlershots.get();
            stradllervengeance = AMIConfigHolder.INTERACT.stradllervengeance.get();
            stradpolebobup = AMIConfigHolder.INTERACT.stradpolebobup.get();
            sugarrush = AMIConfigHolder.INTERACT.sugarrush.get();
            terrapinstomp = AMIConfigHolder.INTERACT.terrapinstomp.get();
            tigerhuntnight = AMIConfigHolder.INTERACT.tigerhuntnight.get();
            warpedcannibalism = AMIConfigHolder.INTERACT.warpedcannibalism.get();
            weakened = AMIConfigHolder.INTERACT.weakened.get();
            warpedtarantula = AMIConfigHolder.INTERACT.warpedtarantula.get();
            cavespidereats = AMIConfigHolder.INTERACT.cavespidereats.get();
            emueggattack = AMIConfigHolder.INTERACT.emueggattack.get();
            caimaneggattack = AMIConfigHolder.INTERACT.caimaneggattack.get();
            mudskipperhunt = AMIConfigHolder.INTERACT.mudskipperhunt.get();
            hummingfollowflutter = AMIConfigHolder.INTERACT.hummingfollowflutter.get();




        } catch (Exception e) {
            LOGGER.warn("An exception was caused trying to load the config for Alex's Interaction.");
            e.printStackTrace();
        }
    }

}
